# docker compose down; docker compose up --remove-orphans;

# 9000 – event-saver
# 9001 – clickhouse
# 9002 – loki
# 9003 – grafana

version: '3.7'

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.4.1-alpine
    restart: always
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ./clickhouse/config/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse/config/users.d:/etc/clickhouse-server/users.d
      - ./clickhouse/init:/docker-entrypoint-initdb.d
      - ./clickhouse/benchmark:/benchmark
    networks:
      - default
      - wotstat-db
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  clickhouse-backup:
    image: altinity/clickhouse-backup:2.4.29
    restart: always
    volumes_from:
      - clickhouse
    volumes:
      - ./clickhouse-backup/start.sh:/start.sh
    depends_on:
      - clickhouse
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_USERNAME=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - S3_BUCKET=wotstat-backup
      - S3_ENDPOINT=https://storage.yandexcloud.net
      - S3_REGION=ru-central1
      - S3_STORAGE_CLASS=GLACIER # <==> ICE
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - REMOTE_STORAGE=s3
      - API_LISTEN=0.0.0.0:7171
      - WATCH_INTERVAL=24h
      - FULL_INTERVAL=168h
    networks:
      - default

  redis:
    container_name: redis
    image: 'redis:alpine'
    restart: always
    networks:
      - default

  event-saver:
    container_name: event-saver
    restart: always
    user: "1000:1000"
    depends_on:
      - clickhouse
      - redis
    environment:
      - PORT=9000
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_DATABASE=WOT
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
      - REDIS_HOST=redis
      - JWT_SECRET
      - WG_API_KEY
    networks:
      - default

  loki:
    container_name: loki
    restart: always
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki/loki-local.yaml:/etc/loki/loki-config.yaml
    networks:
      - default

  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:10.3.3
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
    networks:
      - default

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: '1450'
  wotstat-db:
    driver: bridge
