# docker compose down; docker compose up --remove-orphans;

version: '3.7'

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.8.9-alpine
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ../clickhouse/data:/var/lib/clickhouse
      - ../clickhouse/log:/var/log/clickhouse-server
      - ./clickhouse/config/config.d:/etc/clickhouse-server/config.d
      # - ./clickhouse/users.d:/etc/clickhouse-server/users.d
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    ports:
      - '9001:8123'
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  enent-saver:
    container_name: enent-saver
    image: ghcr.io/wot-stat/eventsaver:main
    restart: always
    ports:
     - "9000:9000"
    depends_on:
      - clickhouse
      - redis
    environment:
      - PORT=9000
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - REDIS_HOST=redis
      - CLICKHOUSE_DATABASE=WOT
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
      - JWT_SECRET
      - DEBUG=1

