# docker compose -p prod -f docker-compose.yaml -f docker-compose.prod.yaml up;
 
version: '3.7'

x-logging: &loki-logging-prod
  driver: loki
  options:
    loki-url: "http://localhost:9002/loki/api/v1/push"
    loki-retries: 2
    loki-timeout: 1s
    loki-max-backoff: 800ms
    max-size: "10m"
    max-file: "3"

services:
  clickhouse:
    container_name: clickhouse-prod
    logging: *loki-logging-prod
    volumes:
      - ../clickhouse/data:/var/lib/clickhouse
      - ../clickhouse/log:/var/log/clickhouse-server
    ports:
      - '9001:8123'

  clickhouse-backup:
    container_name: clickhouse-backup-prod
    command: ["/bin/bash", "/start.sh"]
    environment:
      - WATCH_BACKUP_NAME_TEMPLATE=prod-{type}-{time:2006-01-02T15-04-05}
      - LOG_LEVEL=warn

  redis:
    container_name: redis-prod
    logging: *loki-logging-prod

  loki:
    container_name: loki-prod
    logging: *loki-logging-prod
    volumes:
      - ../loki-data:/tmp/loki
    ports:
      - "9002:3100"

  grafana:
    container_name: grafana-prod
    logging: *loki-logging-prod
    ports:
      - "9003:3000"

  enent-saver:
    container_name: enent-saver-prod
    logging: *loki-logging-prod
    image: ghcr.io/wot-stat/eventsaver:main
    ports:
     - "9000:9000"
    environment:
      - DEBUG=1
      - ASYNC_INSERT=1


