apiVersion: 1

# deleteDatasources:
#   - name: loki

datasources:
  - name: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: \"trace_id\":\"(\w+)\"
          name: TraceID
          url: $${__value.raw}
