name: deployment

on:
  push:
    branches: [main]
  workflow_dispatch:
    # inputs:
    #   dependencies:
    #     type: choice
    #     description: 'What to do with **dependencies**'
    #     required: true
    #     default: install
    #     options:
    #       - install
    #       - update
    #       - nothing

# concurrency: staging

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy .env
        env:
          DOTENV: ${{ secrets.DOTENV }}
        run: cat <<< "$DOTENV" > .env

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host node
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Copy to server
        run: rsync -avz ./ node:/${{ vars.APP_PATH }}

      # - name: Install Dependencies
      #   if: github.event.inputs.dependencies == 'install'
      #   run: ssh node "cd ${{ vars.APP_PATH }}; bash deps.install.sh"

      # - name: Update Dependencies
      #   if: github.event.inputs.dependencies == 'update'
      #   run: ssh node "cd ${{ vars.APP_PATH }}; bash deps.update.sh"

      # - name: Authorize in ghcr.io with PAT
      #   run: ssh node "docker login ghcr.io -u ${{ secrets.GHCR_PAT_USER }} -p ${{ secrets.GHCR_PAT }}"

      - name: Startup docker-compose
        run: ssh node "cd ${{ vars.APP_PATH }}; bash rerun.sh"
