name: deployment

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      dependencies:
        type: choice
        description: 'Select environment to deploy'
        required: true
        default: dev
        options:
          - all
          - dev
          - prod

# concurrency: staging

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy .env
        env:
          DOTENV: ${{ secrets.DOTENV }}
        run: cat <<< "$DOTENV" > .env

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host node
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Copy to server
        run: rsync -avz ./ node:/${{ vars.APP_PATH }}

      - name: Startup docker-compose ALL
        if: ${{ github.event.inputs.option == 'all' || github.event_name == 'push' }}
        run: ssh node "cd ${{ vars.APP_PATH }}; bash rerun-dev.sh && bash rerun-prod.sh"

      - name: Startup docker-compose DEV
        if: ${{ github.event.inputs.option == 'dev' }}
        run: ssh node "cd ${{ vars.APP_PATH }}; bash rerun-dev.sh"

      - name: Startup docker-compose PROD
        if: ${{ github.event.inputs.option == 'prod' }}
        run: ssh node "cd ${{ vars.APP_PATH }}; bash rerun-prod.sh"
